import { Image1, RentTicket } from "assets/images";

export const TitleArray = () => {
  return [
    {
      id: 1,
      coverImage: Image1,
      title: "Memorize",
      authors: "Suho Rekt",
      genre: { genre: "Action World travel Romantic" },
      summary: `Nhưng tôi phải giải thích cho bạn hiểu làm thế nào mà tất cả ý tưởng sai lầm về việc tố cáo niềm vui và ca ngợi nỗi đau đã ra đời và tôi sẽ cung cấp cho bạn một bản tường trình đầy đủ về hệ thống, cũng như giải thích những lời dạy thực tế của nhà thám hiểm chân lý vĩ đại, Người xây dựng nên hạnh phúc của con người. Không ai từ chối, không thích hay tránh xa thú vui, vì nó là thú vui, mà vì những ai không biết theo đuổi thú vui một cách hợp lý sẽ gặp phải những hậu quả vô cùng đau đớn.`,
      totalChapter: 52,
      point: 25,
      coin: 45,
      like: 1012030,
      view: 725813,
      rank: 1,
      schedule: "T3",
      status: "finished",
      chargeTime: 6,
      approveStatus: 3, // TODO: 0: đã duyệt, 1: chờ duyệt, 2: từ chối, 3: bản nháp
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 18, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 2,
      coverImage: Image1,
      title: "Memorize 2 nogel j ijf oidsjfs oisdjf",
      authors: "Suho Rekt",
      genre: { genre: "Action World travel Romantic" },
      summary: `Nhưng tôi phải giải thích cho bạn hiểu làm thế nào mà tất cả ý tưởng sai lầm về việc tố cáo niềm vui và ca ngợi nỗi đau đã ra đời và tôi sẽ cung cấp cho bạn một bản tường trình đầy đủ về hệ thống, cũng như giải thích những lời dạy thực tế của nhà thám hiểm chân lý vĩ đại, Người xây dựng nên hạnh phúc của con người. Không ai từ chối, không thích hay tránh xa thú vui, vì nó là thú vui, mà vì những ai không biết theo đuổi thú vui một cách hợp lý sẽ gặp phải những hậu quả vô cùng đau đớn.`,
      totalChapter: 52,
      point: 25,
      coin: 45,
      like: 1012030,
      view: 725813,
      rank: 1,
      schedule: "T3",
      status: "finished",
      chargeTime: 6,
      approveStatus: 3,
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 18, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 3,
      coverImage: Image1,
      title: "Memorize 3",
      authors: "Suho Rekt",
      genre: { genre: "Action World travel Romantic" },
      summary: `Nhưng tôi phải giải thích cho bạn hiểu làm thế nào mà tất cả ý tưởng sai lầm về việc tố cáo niềm vui và ca ngợi nỗi đau đã ra đời và tôi sẽ cung cấp cho bạn một bản tường trình đầy đủ về hệ thống, cũng như giải thích những lời dạy thực tế của nhà thám hiểm chân lý vĩ đại, Người xây dựng nên hạnh phúc của con người. Không ai từ chối, không thích hay tránh xa thú vui, vì nó là thú vui, mà vì những ai không biết theo đuổi thú vui một cách hợp lý sẽ gặp phải những hậu quả vô cùng đau đớn.`,
      totalChapter: 52,
      point: 25,
      coin: 45,
      like: 1012030,
      view: 725813,
      rank: 1,
      schedule: "T3",
      status: "finished",
      chargeTime: 6,
      approveStatus: 3,
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 18, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 4,
      coverImage: Image1,
      title: "Memorize 4",
      authors: "Suho Rekt",
      genre: { genre: "Action World travel Romantic" },
      summary: `Nhưng tôi phải giải thích cho bạn hiểu làm thế nào mà tất cả ý tưởng sai lầm về việc tố cáo niềm vui và ca ngợi nỗi đau đã ra đời và tôi sẽ cung cấp cho bạn một bản tường trình đầy đủ về hệ thống, cũng như giải thích những lời dạy thực tế của nhà thám hiểm chân lý vĩ đại, Người xây dựng nên hạnh phúc của con người. Không ai từ chối, không thích hay tránh xa thú vui, vì nó là thú vui, mà vì những ai không biết theo đuổi thú vui một cách hợp lý sẽ gặp phải những hậu quả vô cùng đau đớn.`,
      totalChapter: 52,
      point: 25,
      coin: 45,
      like: 1012030,
      view: 725813,
      rank: 1,
      schedule: "T3",
      status: "finished",
      chargeTime: 6,
      approveStatus: 3,
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 18, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 5,
      coverImage: Image1,
      title: "Memorize 5",
      authors: "Suho Rekt",
      genre: { genre: "Action World travel Romantic" },
      summary: `Nhưng tôi phải giải thích cho bạn hiểu làm thế nào mà tất cả ý tưởng sai lầm về việc tố cáo niềm vui và ca ngợi nỗi đau đã ra đời và tôi sẽ cung cấp cho bạn một bản tường trình đầy đủ về hệ thống, cũng như giải thích những lời dạy thực tế của nhà thám hiểm chân lý vĩ đại, Người xây dựng nên hạnh phúc của con người. Không ai từ chối, không thích hay tránh xa thú vui, vì nó là thú vui, mà vì những ai không biết theo đuổi thú vui một cách hợp lý sẽ gặp phải những hậu quả vô cùng đau đớn.`,
      totalChapter: 52,
      point: 25,
      coin: 45,
      like: 1012030,
      view: 725813,
      rank: 1,
      schedule: "T3",
      status: "finished",
      chargeTime: 6,
      approveStatus: 3,
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 18, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 6,
      coverImage: Image1,
      title: "Memorize 6",
      authors: "Suho Rekt",
      genre: { genre: "Action World travel Romantic" },
      summary: `Nhưng tôi phải giải thích cho bạn hiểu làm thế nào mà tất cả ý tưởng sai lầm về việc tố cáo niềm vui và ca ngợi nỗi đau đã ra đời và tôi sẽ cung cấp cho bạn một bản tường trình đầy đủ về hệ thống, cũng như giải thích những lời dạy thực tế của nhà thám hiểm chân lý vĩ đại, Người xây dựng nên hạnh phúc của con người. Không ai từ chối, không thích hay tránh xa thú vui, vì nó là thú vui, mà vì những ai không biết theo đuổi thú vui một cách hợp lý sẽ gặp phải những hậu quả vô cùng đau đớn.`,
      totalChapter: 52,
      point: 25,
      coin: 45,
      like: 1012030,
      view: 725813,
      rank: 1,
      schedule: "T3",
      status: "finished",
      chargeTime: 6,
      approveStatus: 3,
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 18, 23, 16, 0, 0).toISOString(),
    },
  ];
};

export const ChapterArray = () => {
  return [
    {
      id: 1,
      order: 1,
      title: 'Ch.1: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 2,
      order: 2,
      title: 'Ch.2: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 3,
      order: 3,
      title: 'Ch.3: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 4,
      order: 4,
      title: 'Ch.4: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 5,
      order: 5,
      title: 'Ch.5: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 6,
      order: 6,
      title: 'Ch.6: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 7,
      order: 7,
      title: 'Ch.7: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 8,
      order: 8,
      title: 'Ch.8: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 9,
      order: 9,
      title: 'Ch.9: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 10,
      order: 10,
      title: 'Ch.10: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 11,
      order: 11,
      title: 'Ch.11: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 12,
      order: 12,
      title: 'Ch.12: "Xuyen nhanh" co gi an khong?',
      coverImage: Image1,
      free: false,
      charge: true,
      coin: true,
      point: true,
      like: 5513,
      approveStatus: 3,
      releaseDay: "20/10/2020",
      schedule: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      updatedAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
  ];
};

export const UserArray = () => {
  return [
    {
      userID: 1,
      userName: "G091321897",
      buyTicket: 1,
      rentTicket: 2,
      coin: 23,
      point: 95,
      startCountdown: new Date(2022, 7, 26, 23, 10, 0, 0).toISOString(),
      endCountdown: new Date(2022, 7, 27, 3, 0, 0, 0).toISOString(),
      chapterID: 1,
      paid: false,
    },
  ];
};

export const NoticeArray = () => {
  return [
    {
      id: 1,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 2,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 3,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 4,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 5,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 6,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 7,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 8,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 9,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
    {
      id: 10,
      coverImage: Image1,
      title: "Thông báo đăng ký.",
      subTitle: "Comico xin thông báo ngừng cung cấp",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat ratione nemo alias velit at, cumque aperiam minima ipsa placeat sed? Aliquam ullam quibusdam commodi error amet molestiae, et tempore perspiciatis.",
      createdAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
  ];
};

export const TitleTicket = () => {
  return [
    {
      id: 1,
      title: "Memorize",
      titleImage: Image1,
      ticketImage: RentTicket,
      ticket: 1,
      beginAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
      expiredAt: new Date(2022, 7, 16, 23, 16, 0, 0).toISOString(),
    },
  ];
};
