@baseUrl = http://localhost:3001/api
@table = /ticket-histories

# @name getAll

GET {{baseUrl}}{{table}}?userId=1&_sort=createdAt&_order=desc HTTP/1.1

###

# @name getOne

GET {{baseUrl}}{{table}}/1 HTTP/1.1

###

# @name filter

GET {{baseUrl}}{{table}}?schedule=T4 HTTP/1.1

###

# @name paginate

GET {{baseUrl}}{{table}}?_page=1&_limit=2 HTTP/1.1

###

# @name sort

GET {{baseUrl}}{{table}}?_sort=rank&_order=asc&_limit=2 HTTP/1.1

###

# @name search

GET {{baseUrl}}{{table}}?q=le HTTP/1.1

###

GET {{baseUrl}}{{table}}?schedule_like=T6 HTTP/1.1

###

# @name childrenResource

# GET {{baseUrl}}{{table}}?_embed=comments HTTP/1.1
GET {{baseUrl}}/genres?_embed=titles HTTP/1.1

###

# @name parentResource

GET {{baseUrl}}/{{table}}?_expand=titleStatus HTTP/1.1


###

# @name create

POST {{baseUrl}}{{table}} HTTP/1.1
Content-Type: application/json

{
	"name": "Foobar",
	"title": "Phone"
}

###

# @name update

PATCH {{baseUrl}}{{table}}/2 HTTP/1.1
Content-Type: application/json

{
	"title": "PC"
}

###

# @name delete

DELETE {{baseUrl}}{{table}}/2 HTTP/1.1